#CC = gcc
#CFLAGS = -Wall
#EXEC = mon_prog

#all: $(EXEC)

#$(EXEC): LC.o foncton.o
#	$(CC) $(CFLAGS) -o $@ $^
#LC.o: LC.c fonction.h
#	$(CC) $(CFLAGS) -o $@ $<

#fonction.o: fonction.c fonction.h
#	$(CC) $(CFLAGS) -o $@ $<

#clean:
#	rm -f *.o $(EXEC):
snake:
	gcc main.c fonction_snake.c -lncurses -o snake
